#!/usr/bin/env bash


imply() {

    if [[ -z $1 ]] || [[ $1 == '-' ]]; then
        input="/dev/stdin"
    else
        input="$1"
    fi

    if [[ -n $2 ]]; then
        output="$2"
    else
        output="/dev/stdout"
    fi

    envsubst < "$input" > "$output"
}